# Generated by Django 4.2.6 on 2023-11-01 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('created_date_of_product', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('ЗАВОД', 'Завод'), ('ДИСТРИБЬЮТОР', 'Дистрибьютор'), ('ДИЛЕРСКИЙ ЦЕНТР', 'Дилерский центр'), ('КРУПНАЯ РОЗНИЧНАЯ СЕТЬ', 'Крупная розничная сеть'), ('ИП', 'ИП')], max_length=128, verbose_name='Тип сети')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('debt_to_provider', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='RelatedProviderToProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Продукт')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт-Поставщик',
                'verbose_name_plural': 'Продукты-Поставщики',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(related_name='products', through='api.RelatedProviderToProduct', to='api.provider'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.provider', verbose_name='Сеть')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотруники',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('building_number', models.IntegerField(verbose_name='Номер дома')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.provider', verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
