# Generated by Django 4.2.6 on 2023-10-27 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 9, 50, 22, 885260), verbose_name='Время создания'),
        ),
    ]
