# Generated by Django 4.2.6 on 2023-10-27 08:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_provider_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='employees',
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.provider', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.provider', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.provider', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 27, 21, 221913), verbose_name='Время создания'),
        ),
    ]
