# Generated by Django 4.2.6 on 2023-10-27 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_company_alter_provider_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedprovidertoproduct',
            options={'verbose_name': 'Продукт-Поставщик', 'verbose_name_plural': 'Продукты-Поставщики'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 47, 57, 608755), verbose_name='Время создания'),
        ),
    ]
