# Generated by Django 4.2.6 on 2023-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_company_alter_provider_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('ЗАВОД', 'Завод'), ('ДИСТРИБЬЮТОР', 'Дистрибьютор'), ('ДИЛЕРСКИЙ ЦЕНТР', 'Дилерский центр'), ('КРУПНАЯ РОЗНИЧНАЯ СЕТЬ', 'Крупная розничная сеть'), ('ИП', 'ИП')], max_length=128, verbose_name='Тип сети'),
        ),
    ]
